# Jekyll GH-pages Digital Collection Generator

# Site settings
title: Digital Collection Template
description: Template for creating digital collection website with Jekyll
keywords: idaho, digital collections, history, photographs
owner: University of Idaho Library
email: ewilliamson@uidaho.edu

# url variables
# url = your domain, on gh-pages username.github.io
url: https://uidaholib.github.io
# baseurl = the path where the site will appear under, on gh-pages the repo name
baseurl: /collection-template
# the database where your images are stored
dburl: http://digital.lib.uidaho.edu/cdm/search/collection/

# jekyll collections settings
collections:
  home:
    output: true
    permalink: /:title/
  digital_collections:
    output: true
    permalink: /:path/
